Repository dwip708/EcoFusion, pull requests merged in 2024-10, with the labels that each got.

#2 Debugged Routing Issues and Implement Responsive Contact Form
  src/App.js
  src/components/ContactUs.css
  src/components/ContactUs.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#7 designed profile page
  package-lock.json
  package.json
  src/components/Profile.css
  src/components/Profile.js
Labels: enhancement, good first issue, hacktoberfest-accepted, advanced

#9 Cart styles, profile file components changed.
  src/components/CartPage.css
  src/components/CartPage.js
  src/components/CustomNavbar.js
  src/components/Profile.js
  src/components/ProfileComponents/PersonalInformation.css
  src/components/ProfileComponents/PersonalInformation.js
Labels: hacktoberfest-accepted

#23 Chore: Improved the overall cart UI including empty cart
  src/components/CartPage.css
  src/components/CartPage.js
Labels: frontend, hacktoberfest-accepted, advanced

#24 Improved the product card in Homepage
  src/components/HomePage.css
  src/components/HomePage.js
Labels: hacktoberfest-accepted
